apiVersion: v1
# Определяем тип объекта как Service, который позволяет обеспечивать доступ к одному или нескольким подам приложения через определенный IP-адрес и порт
kind: Service

# Задаем имя сервиса как myapp-service
metadata:
  name: my-app-service
spec:
  # Здесь указывается, что сервис будет направлять трафик на поды с меткой app: myapp
  selector:
    app: my-app
    # Определяем порт, на котором сервис будет прослушивать трафик (80), и порт, на котором поды приложения слушают входящие соединения (8080)
  ports:
    - protocol: TCP
      # С порта 80
      port: 80
      # На порт 8000 (Порт, который прослушивает контейнер)
      targetPort: 8000
  type: NodePort